In [2]:
import requests
import pandas as pd
from lxml import etree
import json

https://movie.douban.com/tag/#/?sort=U&range=0,10&tags=%E5%8A%A8%E7%94%BB

In [13]:
url='https://music.douban.com/top250'
headers={'User-Agent':'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36'}
b='bid=<YOUR_BID>; _vwo_uuid_v2=D59AC51BC0C8DC3659831FEF855201CE9|139d0cb11657fa3ec35701d9b39cb08c; gr_user_id=a3ee981a-7cbd-4f79-abcc-a1bb9c439290; __gads=ID=e29d3a6975f5705b:T=1578526650:S=ALNI_MakJixAUM_fECO5RxxO1OXwECDU9A; ll="118371"; trc_cookie_storage=taboola%2520global%253Auser-id%3D316670c5-974f-4a1d-bca1-b1468f11dac3-tuct4f517ca; __yadk_uid=4qUCa157BbRiORs96PyQmeeXS1lDqYhk; douban-profile-remind=1; __utmz=223695111.1579659800.2.2.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; douban-fav-remind=1; viewed="3040149_2995812_30199061_4011670_33439842_30253066_26997029"; _ga=GA1.2.1427742213.1578526647; push_noty_num=0; push_doumail_num=0; cto_bundle=kMPNCl9Wbm04bE9yNk1IbFl3MkhLSSUyQlZQSElYc0pWTXMlMkZYTHIlMkIlMkJQaFRBUUNveEVXMkIwTktIMUV1OG1TSU5xczVRSDRHS3JuZ1laOVlwc3ZYTzk3VlR4WVdMeGpNS1hsQ01ORFdzQXBQamYxa0R4cUZIaGhiYUpFR1FVY2s0Q2ROMTRvM1dwMGJhOEFiT0ZadnRuMHZ4MyUyRkpRJTNEJTNE; __utmz=30149280.1589079646.29.19.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1589097016%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1427742213.1578526647.1589079646.1589097017.30; __utmc=30149280; __utma=223695111.1692093362.1578813832.1588940662.1589097017.5; __utmb=223695111.0.10.1589097017; __utmc=223695111; ap_v=0,6.0; dbcl2="216584294:NBHisAJp02A"; ck=jzQy; __utmt=1; __utmv=30149280.21658; __utmb=30149280.6.10.1589097017; _pk_id.100001.4cf6=0622253e80c3deb2.1578813831.5.1589097344.1588943550.'
line=b.split(';')
cookie={}
for i in line:
    key,value = i.split('=',1)
    cookie[key] = value
    
response = requests.get(url,headers=headers,cookies=cookie)

In [12]:
print(response.status_code)

200

In [15]:
response.encoding = 'utf-8'
html = response.text
html

'<!DOCTYPE html>\n<html lang="zh-CN" class="ua-android ua-webkit">\n<head>\n    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n    <meta name="renderer" content="webkit">\n    <meta name="referrer" content="always">\n    <meta name="google-site-verification" content="ok0wCgT20tBBgo9_zat2iAcimtN4Ftf5ccsh092Xeyw" />\n    <title>\n豆瓣音乐 Top 250\n</title>\n    \n    <meta http-equiv="Pragma" content="no-cache">\n    <meta http-equiv="Expires" content="Sun, 6 Mar 2005 01:00:00 GMT">\n    \n    <script >var _head_start = new Date();</script>\n    <script src="https://img9.doubanio.com/f/music/b66ed708717bf0b4a005a4d0113af8843ef3b8ff/js/music/lib/jquery-1.11.0.min.js"></script>\n    <script src="https://img9.doubanio.com/f/music/dcd7ea79bfc24a0b5d9a280a8ca59acceddd56be/js/music/lib/jquery-migrate-1.2.1.js"></script>\n    <script src="https://img9.doubanio.com/f/shire/5ecaf46d6954d5a30bc7d99be86ae34031646e00/js/douban.js"></script>\n    <script src="https://img9.doubanio.com/f/shire/77323ae72a612bba8b65f845491513ff3329b1bb/js/do.js" data-cfg-autoload="false"></script>\n    <link href="https://img9.doubanio.com/f/shire/6af0151e6607336ae329fd87532acdd0fe7b74fd/css/douban.css" rel="stylesheet" type="text/css">\n    <link href="https://img9.doubanio.com/f/music/6276708bd0b43f4891f02f84a0c66e5241bea03e/css/music/init.css" rel="stylesheet" type="text/css" />\n    <style type="text/css">\n    \n    \n    </style>\n    \n  <link rel="stylesheet" type="text/css" href="https://img9.doubanio.com/f/music/d8f0251a1581979db1411c733055ca3910cc1543/css/music/_init_.css"/>\n\n    <!-- COLLECTED CSS -->\n    <script></script>\n\n    <link rel="shortcut icon" href="https://img9.doubanio.com/favicon.ico" type="image/x-icon">\n</head>\n\n<body>\n  \n    <script type="text/javascript">var _body_start = new Date();</script>\n    \n       \n\n\n\n    <link href="//img3.doubanio.com/dae/accounts/resources/527f922/shire/bundle.css" rel="stylesheet" type="text/css">\n\n\n\n<div id="db-global-nav" class="global-nav">\n  <div class="bd">\n    \n<div class="top-nav-info">\n  <a href="https://accounts.douban.com/passport/login?source=music" class="nav-login" rel="nofollow">登录/注册</a>\n</div>\n\n\n    <div class="top-nav-doubanapp">\n  <a href="https://www.douban.com/doubanapp/app?channel=top-nav" class="lnk-doubanapp">下载豆瓣客户端</a>\n  <div id="doubanapp-tip">\n    <a href="https://www.douban.com/doubanapp/app?channel=qipao" class="tip-link">豆瓣 <span class="version">6.0</span> 全新发布</a>\n    <a href="javascript: void 0;" class="tip-close">×</a>\n  </div>\n  <div id="top-nav-appintro" class="more-items">\n    <p class="appintro-title">豆瓣</p>\n    <p class="qrcode">扫码直接下载</p>\n    <div class="download">\n      <a href="https://www.douban.com/doubanapp/redirect?channel=top-nav&direct_dl=1&download=iOS">iPhone</a>\n      <span>·</span>\n      <a href="https://www.douban.com/doubanapp/redirect?channel=top-nav&direct_dl=1&download=Android" class="download-android">Android</a>\n    </div>\n  </div>\n</div>\n\n    \n\n\n<div class="global-nav-items">\n  <ul>\n    <li class="">\n      <a href="https://www.douban.com" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-main&quot;,&quot;uid&quot;:&quot;0&quot;}">豆瓣</a>\n    </li>\n    <li class="">\n      <a href="https://book.douban.com" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-book&quot;,&quot;uid&quot;:&quot;0&quot;}">读书</a>\n    </li>\n    <li class="">\n      <a href="https://movie.douban.com" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-movie&quot;,&quot;uid&quot;:&quot;0&quot;}">电影</a>\n    </li>\n    <li class="on">\n      <a href="https://music.douban.com"  data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-music&quot;,&quot;uid&quot;:&quot;0&quot;}">音乐</a>\n    </li>\n    <li class="">\n      <a href="https://www.douban.com/location" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-location&quot;,&quot;uid&quot;:&quot;0&quot;}">同城</a>\n    </li>\n    <li class="">\n      <a href="https://www.douban.com/group" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-group&quot;,&quot;uid&quot;:&quot;0&quot;}">小组</a>\n    </li>\n    <li class="">\n      <a href="https://read.douban.com&#47;?dcs=top-nav&amp;dcm=douban" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-read&quot;,&quot;uid&quot;:&quot;0&quot;}">阅读</a>\n    </li>\n    <li class="">\n      <a href="https://douban.fm&#47;?from_=shire_top_nav" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-fm&quot;,&quot;uid&quot;:&quot;0&quot;}">FM</a>\n    </li>\n    <li class="">\n      <a href="https://time.douban.com&#47;?dt_time_source=douban-web_top_nav" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-time&quot;,&quot;uid&quot;:&quot;0&quot;}">时间</a>\n    </li>\n    <li class="">\n      <a href="https://market.douban.com&#47;?utm_campaign=douban_top_nav&amp;utm_source=douban&amp;utm_medium=pc_web" target="_blank" data-moreurl-dict="{&quot;from&quot;:&quot;top-nav-click-market&quot;,&quot;uid&quot;:&quot;0&quot;}">豆品</a>\n    </li>\n  </ul>\n</div>\n\n  </div>\n</div>\n<script>\n  ;window._GLOBAL_NAV = {\n    DOUBAN_URL: "https://www.douban.com",\n    N_NEW_NOTIS: 0,\n    N_NEW_DOUMAIL: 0\n  };\n</script>\n\n\n\n    <script src="//img3.doubanio.com/dae/accounts/resources/527f922/shire/bundle.js" defer="defer"></script>\n\n\n\n\n       \n\n\n\n    <link href="//img3.doubanio.com/dae/accounts/resources/527f922/music/bundle.css" rel="stylesheet" type="text/css">\n\n\n\n\n<div id="db-nav-music" class="nav">\n  <div class="nav-wrap">\n  <div class="nav-primary">\n    <div class="nav-logo">\n      <a href="https:&#47;&#47;music.douban.com">豆瓣音乐</a>\n    </div>\n    <div class="nav-search">\n      <form action="https:&#47;&#47;search.douban.com&#47;music/subject_search" method="get">\n        <fieldset>\n          <legend>搜索：</legend>\n          <label for="inp-query">\n          </label>\n          <div class="inp"><input id="inp-query" name="search_text" size="22" maxlength="60" placeholder="唱片名、表演者、条码、ISRC" value=""></div>\n          <div class="inp-btn"><input type="submit" value="搜索"></div>\n          <input type="hidden" name="cat" value="1003" />\n        </fieldset>\n      </form>\n    </div>\n  </div>\n  </div>\n  <div class="nav-secondary">\n    \n\n<div class="nav-items">\n  <ul>\n    <li    ><a href="https://music.douban.com/artists/"\n     >音乐人</a>\n    </li>\n    <li    ><a href="https://www.douban.com/wetware/"\n     >潮潮豆瓣音乐周</a>\n    </li>\n    <li    ><a href="https://music.douban.com/artists/royalty/"\n     >金羊毛计划</a>\n    </li>\n    <li    ><a href="https://music.douban.com/topics/"\n     >专题</a>\n    </li>\n    <li    ><a href="https://music.douban.com/chart"\n     >排行榜</a>\n    </li>\n    <li    ><a href="https://music.douban.com/tag/"\n     >分类浏览</a>\n    </li>\n    <li    ><a href="https://music.douban.com/review/latest/"\n     >乐评</a>\n    </li>\n    <li    ><a href="https://douban.fm/?from_=music_nav"\n     >豆瓣FM</a>\n    </li>\n    <li    ><a href="https://douban.fm/explore/songlists/"\n     >歌单</a>\n    </li>\n    <li    ><a href="https://music.douban.com/annual/2019?source=navigation"\n            target="_blank"\n     >2019年度榜单</a>\n    </li>\n    <li    ><a href="https://artist.douban.com/abilu/"\n     >阿比鹿音乐奖</a>\n    </li>\n  </ul>\n</div>\n\n    <a href="https://music.douban.com/annual/2019?source=music_navigation" class="musicannual"></a>\n  </div>\n</div>\n\n<script id="suggResult" type="text/x-jquery-tmpl">\n  <li data-link="{{= url}}">\n            <a href="{{= url}}" onclick="moreurl(this, {from:\'music_search_sugg\', query:\'{{= keyword }}\', subject_id:\'{{= id}}\', i: \'{{= index}}\', type: \'{{= type}}\'})">\n            <img src="{{= pic}}" width="40" />\n            <div>\n                <em>{{= title}}</em>\n                {{if type == "m"}}\n                    <span>(艺术家)</span>\n                {{else type == "a"}}\n                    <span>(音乐人)</span>\n                {{else type == "d"}}\n                    <span>(DJ)</span>\n                {{else type == "l"}}\n                    <span>(厂牌)</span>\n                {{/if}}\n                {{if other_title}}\n                    <span>其他名称：{{= other_title}}</span>\n                {{/if}}\n                {{if performer}}\n                    <p>表演者：{{= performer}}</p>\n                {{/if}}\n                {{if cn_name}}\n                    <p>{{= cn_name}}</p>\n                {{/if}}\n                {{if en_name}}\n                    <p>{{= en_name}}</p>\n                {{/if}}\n            </div>\n        </a>\n        </li>\n  </script>\n\n\n\n\n    <script src="//img3.doubanio.com/dae/accounts/resources/527f922/music/bundle.js" defer="defer"></script>\n\n\n\n\n\n    <div id="wrapper">\n        \n\n        \n<div id="content">\n    \n    <h1>豆瓣音乐 Top 250</h1>\n\n    <div class="grid-16-8 clearfix">\n        \n        \n        <div class="article">\n               \n  <div class="indent">\n    \n\n        \n        <p class="ul first"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/2995812/" onclick="moreurl(this,{i:\'0\',query:\'\',subject_id:\'2995812\',from:\'music_subject_search\'})" title="Jason Mraz - We Sing. We Dance. We Steal Things."  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s2967252.jpg" alt="Jason Mraz - We Sing. We Dance. We Steal Things." style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/2995812/" onclick="moreurl(this,{i:\'0\',query:\'\',subject_id:\'2995812\',from:\'music_subject_search\'})" >\n            We Sing. We Dance. We Steal Things.\n       </a>\n\n            <p class="pl">Jason Mraz / 2008-05-13 / Import / Audio CD / 民谣</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">9.1</span>\n                <span class="pl">\n                    (\n                            112303人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_2995812"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/3040149/" onclick="moreurl(this,{i:\'1\',query:\'\',subject_id:\'3040149\',from:\'music_subject_search\'})" title="Coldplay - Viva La Vida"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s3054604.jpg" alt="Coldplay - Viva La Vida" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/3040149/" onclick="moreurl(this,{i:\'1\',query:\'\',subject_id:\'3040149\',from:\'music_subject_search\'})" >\n            Viva La Vida\n                <span style="font-size:12px;">Death And All His Friends</span>\n       </a>\n\n            <a class="start_radio" target="_blank" title="试听" href="https://music.douban.com/subject/3040149/?auto_play=1#link-report"></a>\n            <p class="pl">Coldplay / 2008-06-17 / 专辑 / CD / 摇滚</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.7</span>\n                <span class="pl">\n                    (\n                            108328人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_3040149"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/1427374/" onclick="moreurl(this,{i:\'2\',query:\'\',subject_id:\'1427374\',from:\'music_subject_search\'})" title="陈绮贞 - 华丽的冒险"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s1441645.jpg" alt="陈绮贞 - 华丽的冒险" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/1427374/" onclick="moreurl(this,{i:\'2\',query:\'\',subject_id:\'1427374\',from:\'music_subject_search\'})" >\n            华丽的冒险\n                <span style="font-size:12px;">華麗的冒險</span>\n       </a>\n\n            <a class="start_radio" target="_blank" title="试听" href="https://music.douban.com/subject/1427374/?auto_play=1#link-report"></a>\n            <p class="pl">陈绮贞 / 2005-09-23 / 专辑 / CD / 流行</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.9</span>\n                <span class="pl">\n                    (\n                            83168人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_1427374"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/1403307/" onclick="moreurl(this,{i:\'3\',query:\'\',subject_id:\'1403307\',from:\'music_subject_search\'})" title="周杰伦 - 范特西"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s3750422.jpg" alt="周杰伦 - 范特西" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/1403307/" onclick="moreurl(this,{i:\'3\',query:\'\',subject_id:\'1403307\',from:\'music_subject_search\'})" >\n            范特西\n                <span style="font-size:12px;">Fantasy</span>\n       </a>\n\n            <p class="pl">周杰伦 / 2001-09-14 / 专辑 / CD / 流行</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">9.2</span>\n                <span class="pl">\n                    (\n                            140717人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_1403307"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/3259411/" onclick="moreurl(this,{i:\'4\',query:\'\',subject_id:\'3259411\',from:\'music_subject_search\'})" title="五月天 - 後。青春期的詩"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s3316597.jpg" alt="五月天 - 後。青春期的詩" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/3259411/" onclick="moreurl(this,{i:\'4\',query:\'\',subject_id:\'3259411\',from:\'music_subject_search\'})" >\n            後。青春期的詩\n                <span style="font-size:12px;">后青春期的诗</span>\n       </a>\n\n            <a class="start_radio" target="_blank" title="试听" href="https://music.douban.com/subject/3259411/?auto_play=1#link-report"></a>\n            <p class="pl">五月天 / 2008-10-23 / 专辑 / CD / 摇滚</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.8</span>\n                <span class="pl">\n                    (\n                            89901人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_3259411"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/5958397/" onclick="moreurl(this,{i:\'5\',query:\'\',subject_id:\'5958397\',from:\'music_subject_search\'})" title="孙燕姿 - 是时候"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s4653287.jpg" alt="孙燕姿 - 是时候" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/5958397/" onclick="moreurl(this,{i:\'5\',query:\'\',subject_id:\'5958397\',from:\'music_subject_search\'})" >\n            是时候\n                <span style="font-size:12px;">It&#39;s Time</span>\n       </a>\n\n            <p class="pl">孙燕姿 / 2011-03-08 / 专辑 / CD / 流行</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.6</span>\n                <span class="pl">\n                    (\n                            77618人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_5958397"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/3184419/" onclick="moreurl(this,{i:\'6\',query:\'\',subject_id:\'3184419\',from:\'music_subject_search\'})" title="Lenka - Lenka"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s3259484.jpg" alt="Lenka - Lenka" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/3184419/" onclick="moreurl(this,{i:\'6\',query:\'\',subject_id:\'3184419\',from:\'music_subject_search\'})" >\n            Lenka\n       </a>\n\n            <p class="pl">Lenka / 2008-09-23 / 专辑 / Audio CD / 流行</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.5</span>\n                <span class="pl">\n                    (\n                            80453人评价\n                    )\n                </span></div>\n\n        </div>\n        </td>\n        </tr>\n        </table><div id="collect_form_3184419"></div>\n        \n        <p class="ul"></p>\n        <table width="100%%">\n            <tr class="item">\n                <td width="100" valign="top">\n        \n\n        <a class="nbg" href="https://music.douban.com/subject/3041487/" onclick="moreurl(this,{i:\'7\',query:\'\',subject_id:\'3041487\',from:\'music_subject_search\'})" title="王若琳 - Start from Here"  >\n            <img src="https://img9.doubanio.com/view/subject/s/public/s2874587.jpg" alt="王若琳 - Start from Here" style="width: 80px; max-height: 120px;" />\n        </a>\n        </td>\n        <td valign="top">\n        \n        <div class="pl2">\n        <a href="https://music.douban.com/subject/3041487/" onclick="moreurl(this,{i:\'7\',query:\'\',subject_id:\'3041487\',from:\'music_subject_search\'})" >\n            Start from Here\n                <span style="font-size:12px;">从这里开始</span>\n       </a>\n\n            <p class="pl">王若琳 / 2008-01-11 / 专辑 / CD / 爵士</p>\n\n        \n        \n                    <div class="star clearfix"><span class="allstar45"></span><span class="rating_nums">8.7</span>\n                <span class="pl">\n                    (\n                            72313人评价\n                    )\n                </span></div>\n\n  

In [22]:
s = etree.HTML(html)

title = s.xpath('//*[@id="content"]/div/div[1]/div/table[1]/tr/td[2]/div/a/text()')[0]
score = s.xpath('//*[@id="content"]/div/div[1]/div/table[1]/tr/td[2]/div/div/span[2]/text()')[0]
numbers = s.xpath('//*[@id="content"]/div/div[1]/div/table[1]/tr/td[2]/div/div/span[3]/text()')[0]
print(title,score,numbers)

            We Sing. We Dance. We Steal Things.
        9.1
                    (
                            112303人评价
                    )

In [8]:
name=[]
score=[]
pnumber=[]
url=[]
cover=[]
id=[]
for one in html1:
    name.append(one['title'])
    score.append(one['rate'])
    pnumber.append(one['cover_y'])
    url.append(one['url'])
    cover.append(one['cover'])
    id.append(one['id'])
print(url)

['https://movie.douban.com/subject/1291561/', 'https://movie.douban.com/subject/25662329/', 'https://movie.douban.com/subject/26794435/', 'https://movie.douban.com/subject/20495023/', 'https://movie.douban.com/subject/26683290/', 'https://movie.douban.com/subject/1291560/', 'https://movie.douban.com/subject/30402296/', 'https://movie.douban.com/subject/2129039/', 'https://movie.douban.com/subject/2131459/', 'https://movie.douban.com/subject/1308807/', 'https://movie.douban.com/subject/3287562/', 'https://movie.douban.com/subject/11026735/', 'https://movie.douban.com/subject/1291583/', 'https://movie.douban.com/subject/1301753/', 'https://movie.douban.com/subject/30331149/', 'https://movie.douban.com/subject/1907966/', 'https://movie.douban.com/subject/2353023/', 'https://movie.douban.com/subject/5045678/', 'https://movie.douban.com/subject/26277313/', 'https://movie.douban.com/subject/4202982/']

In [9]:
len(url)

20

In [10]:
columns={'剧名':name,'评分':score,'点评数':pnumber,'url':url,'图片':cover,'id':id}
data=pd.DataFrame(columns)
data.shape

(20, 6)

In [11]:
data

,剧名,评分,点评数,url,图片,id
0,千与千寻,9.4,1560,https://movie.douban.com/subject/1291561/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291561
1,疯狂动物城,9.2,2005,https://movie.douban.com/subject/25662329/,https://img9.doubanio.com/view/photo/s_ratio_p...,25662329
2,哪吒之魔童降世,8.5,8268,https://movie.douban.com/subject/26794435/,https://img9.doubanio.com/view/photo/s_ratio_p...,26794435
3,寻梦环游记,9.1,2048,https://movie.douban.com/subject/20495023/,https://img9.doubanio.com/view/photo/s_ratio_p...,20495023
4,你的名字。,8.4,2000,https://movie.douban.com/subject/26683290/,https://img9.doubanio.com/view/photo/s_ratio_p...,26683290
5,龙猫,9.2,2358,https://movie.douban.com/subject/1291560/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291560
6,天气之子,7.1,8268,https://movie.douban.com/subject/30402296/,https://img9.doubanio.com/view/photo/s_ratio_p...,30402296
7,飞屋环游记,9.0,4000,https://movie.douban.com/subject/2129039/,https://img9.doubanio.com/view/photo/s_ratio_p...,2129039
8,机器人总动员,9.3,4447,https://movie.douban.com/subject/2131459/,https://img9.doubanio.com/view/photo/s_ratio_p...,2131459
9,哈尔的移动城堡,9.1,2131,https://movie.douban.com/subject/1308807/,https://img9.doubanio.com/view/photo/s_ratio_p...,1308807
10,神偷奶爸,8.6,1500,https://movie.douban.com/subject/3287562/,https://img9.doubanio.com/view/photo/s_ratio_p...,3287562
11,超能陆战队,8.7,11811,https://movie.douban.com/subject/11026735/,https://img9.doubanio.com/view/photo/s_ratio_p...,11026735
12,天空之城,9.1,2933,https://movie.douban.com/subject/1291583/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291583
13,狮子王,9.0,3164,https://movie.douban.com/subject/1301753/,https://img9.doubanio.com/view/photo/s_ratio_p...,1301753
14,白蛇：缘起,7.9,7441,https://movie.douban.com/subject/30331149/,https://img9.doubanio.com/view/photo/s_ratio_p...,30331149
15,疯狂原始人,8.7,755,https://movie.douban.com/subject/1907966/,https://img9.doubanio.com/view/photo/s_ratio_p...,1907966
16,驯龙高手,8.7,1920,https://movie.douban.com/subject/2353023/,https://img9.doubanio.com/view/photo/s_ratio_p...,2353023
17,大鱼海棠,6.8,1620,https://movie.douban.com/subject/5045678/,https://img9.doubanio.com/view/photo/s_ratio_p...,5045678
18,西游记之大圣归来,8.3,8268,https://movie.douban.com/subject/26277313/,https://img9.doubanio.com/view/photo/s_ratio_p...,26277313
19,冰雪奇缘,8.4,1969,https://movie.douban.com/subject/4202982/,https://img9.doubanio.com/view/photo/s_ratio_p...,4202982

In [16]:
title=[]
juqing=[]


for i in range(len(data['url'])):
    res=requests.get(data['url'][i],headers=headers,cookies=cookie)
    html = etree.HTML(res.text)
    title.append(''.join(html.xpath('//span/text()')))

AttributeError: 'NoneType' object has no attribute 'xpath'

In [15]:
print(title)

['App用 App 打开查看影人相册99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片、视频评论/剧照打开App查看全部预告片lemon邝言货币与词汇子戈44', 'App用 App 打开聊聊你的观影感受99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片CydenyLauVamei我是卢俊柴斯卡zts', 'App用 App 打开查看导演的其它电影99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片、视频评论/剧照打开App查看全部预告片残月带三星J_Fox嘚嘚嘚嘚嘚二十二岛主五色全味', 'App用 App 打开查看导演的其它电影99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片吉祥鹿阿德动画学术趴王写写peachy', 'App用 App 打开查看影人相册99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片荒也余小岛yihePokerrabbitcarrot', 'App用 App 打开查看影人相册99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片、视频评论/剧照打开App查看全部预告片罗罔极Lindsey落枕儒小沙弥琥珀糖☁️☁️', 'App用 App 打开聊聊你的观影感受99+想看看过\n      即将可播\n    \n        在豆瓣App打开上架提醒\n      预告片/剧照打开App查看全部预告片小水大聪看电影丁萌KOLUGING叶底藏花', 'App用 App 打开聊聊你的观影感受99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片Mia暖言巷陌Ju~曬太陽小姐赝造的孔方兄路小北', 'App用 App 打开查看导演的其它电影99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片、视频评论/剧照打开App查看全部预告片舞！舞！舞！鱼·无[已注销]梅威斯小转铃', 'App用 App 打开查看主演的其它电影99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片音娃Distancerviyu呱啦啦伴你乐行', 'App用 App 打开聊聊你的观影感受99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片守望天堂。越小墨亵渎电影HuanhuanLuc', 'App用 App 打开查看影片获奖情况99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片Dr希鲁鲁克Angelina.aevanKloudFleetwood', 'App用 App 打开查看影片获奖情况99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片隆咚锵索马里难民viyu[已注销]淡淡245', 'App用 App 打开查看导演的其它电影99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片、视频评论/剧照打开App查看全部预告片五乔黑左FF痞子笛时间地理学家', 'App用 App 打开查看影人相册99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片巴塞电影Enjolras肖恩恩恩恩肖桨声灯影L+', 'App用 App 打开关注影评人99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片写剧本的肥树budaphin安德烈大叔大锅新桥妖妖', 'App用 App 打开查看影人相册99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片semifairyTORO VAN DARKO天亮天黑鸟甲[已注销]', 'App用 App 打开关注影评人99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片有心打扰支离疏天马星柚莓玲', 'App用 App 打开关注影评人99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片路人Eita梳子自怜雀斑伊谢尔伦的风小缎', 'App用 App 打开查看影片获奖情况99+想看看过\n      可在线观看\n    \n        打开豆瓣App查看播放源\n      预告片/剧照打开App查看全部预告片五乔高斯控江南赫捍森有机绿植']

In [14]:
columns1={'剧名':title'}
df1=pd.DataFrame(columns1)
df1.head()

SyntaxError: EOL while scanning string literal (<ipython-input-14-d78c9bd16770>, line 1)

In [44]:
da2=pd.concat([data,df1],axis=1)
da2

,剧名,评分,点评数,url,图片,id,剧名,剧情
0,勇敢传说,7.5,3993,https://movie.douban.com/subject/3036473/,https://img9.doubanio.com/view/photo/s_ratio_p...,3036473,,
1,千年女优,8.7,2327,https://movie.douban.com/subject/1307394/,https://img9.doubanio.com/view/photo/s_ratio_p...,1307394,,
2,名侦探柯南：绀碧之棺,6.8,1198,https://movie.douban.com/subject/2357717/,https://img9.doubanio.com/view/photo/s_ratio_p...,2357717,,
3,马达加斯加3,8.2,2000,https://movie.douban.com/subject/3178770/,https://img9.doubanio.com/view/photo/s_ratio_p...,3178770,,
4,麦兜故事,8.5,954,https://movie.douban.com/subject/1302476/,https://img9.doubanio.com/view/photo/s_ratio_p...,1302476,,
5,中华小当家,8.5,696,https://movie.douban.com/subject/2993424/,https://img9.doubanio.com/view/photo/s_ratio_p...,2993424,,
6,海洋之歌,8.8,1353,https://movie.douban.com/subject/11584019/,https://img9.doubanio.com/view/photo/s_ratio_p...,11584019,,
7,女王的柯基,5.8,2133,https://movie.douban.com/subject/30256796/,https://img9.doubanio.com/view/photo/s_ratio_p...,30256796,,
8,鬼妈妈,8.2,1500,https://movie.douban.com/subject/1919245/,https://img9.doubanio.com/view/photo/s_ratio_p...,1919245,,
9,真人快打传奇：蝎子的复仇,7.3,1000,https://movie.douban.com/subject/34875588/,https://img9.doubanio.com/view/photo/s_ratio_p...,34875588,,
10,进击的巨人 第三季 Part.2,9.8,2048,https://movie.douban.com/subject/30353357/,https://img9.doubanio.com/view/photo/s_ratio_p...,30353357,,
11,岁月的童话,8.6,903,https://movie.douban.com/subject/1291588/,https://img9.doubanio.com/view/photo/s_ratio_p...,1291588,,
12,烟花,5.5,2830,https://movie.douban.com/subject/26930504/,https://img9.doubanio.com/view/photo/s_ratio_p...,26930504,,
13,精灵梦叶罗丽7,,530,https://movie.douban.com/subject/34815454/,https://img9.doubanio.com/view/photo/s_ratio_p...,34815454,,
14,夏目友人帐,9.3,672,https://movie.douban.com/subject/3060542/,https://img9.doubanio.com/view/photo/s_ratio_p...,3060542,,
15,七龙珠,9.2,3000,https://movie.douban.com/subject/1782006/,https://img9.doubanio.com/view/photo/s_ratio_p...,1782006,,
16,东京教父,8.9,909,https://movie.douban.com/subject/1310177/,https://img9.doubanio.com/view/photo/s_ratio_p...,1310177,,
17,名侦探柯南：第十一名前锋,6.4,2302,https://movie.douban.com/subject/6984051/,https://img9.doubanio.com/view/photo/s_ratio_p...,6984051,,
18,小蝌蚪找妈妈,8.8,604,https://movie.douban.com/subject/3335371/,https://img9.doubanio.com/view/photo/s_ratio_p...,3335371,,
19,朝花夕誓,7.0,1412,https://movie.douban.com/subject/27083561/,https://img9.doubanio.com/view/photo/s_ratio_p...,27083561,,

In [3]:
for i in range(50):
    
    url='https://movie.douban.com/j/new_search_subjects?sort=U&range=0,10&tags=&start='+str(i*20)+'&genres=%E5%8A%A8%E7%94%BB'
    headers={'User-Agent':'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36'}
    b='bid=<YOUR_BID>; _vwo_uuid_v2=D59AC51BC0C8DC3659831FEF855201CE9|139d0cb11657fa3ec35701d9b39cb08c; gr_user_id=a3ee981a-7cbd-4f79-abcc-a1bb9c439290; __gads=ID=e29d3a6975f5705b:T=1578526650:S=ALNI_MakJixAUM_fECO5RxxO1OXwECDU9A; ll="118371"; trc_cookie_storage=taboola%2520global%253Auser-id%3D316670c5-974f-4a1d-bca1-b1468f11dac3-tuct4f517ca; __yadk_uid=4qUCa157BbRiORs96PyQmeeXS1lDqYhk; douban-profile-remind=1; __utmz=223695111.1579659800.2.2.utmcsr=baidu|utmccn=(organic)|utmcmd=organic|utmctr=%E8%B1%86%E7%93%A3; douban-fav-remind=1; viewed="3040149_2995812_30199061_4011670_33439842_30253066_26997029"; _ga=GA1.2.1427742213.1578526647; push_noty_num=0; push_doumail_num=0; cto_bundle=kMPNCl9Wbm04bE9yNk1IbFl3MkhLSSUyQlZQSElYc0pWTXMlMkZYTHIlMkIlMkJQaFRBUUNveEVXMkIwTktIMUV1OG1TSU5xczVRSDRHS3JuZ1laOVlwc3ZYTzk3VlR4WVdMeGpNS1hsQ01ORFdzQXBQamYxa0R4cUZIaGhiYUpFR1FVY2s0Q2ROMTRvM1dwMGJhOEFiT0ZadnRuMHZ4MyUyRkpRJTNEJTNE; __utmz=30149280.1589079646.29.19.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _pk_ref.100001.4cf6=%5B%22%22%2C%22%22%2C1589097016%2C%22https%3A%2F%2Fwww.baidu.com%2Fs%3Fie%3DUTF-8%26wd%3D%25E8%25B1%2586%25E7%2593%25A3%22%5D; _pk_ses.100001.4cf6=*; __utma=30149280.1427742213.1578526647.1589079646.1589097017.30; __utmc=30149280; __utma=223695111.1692093362.1578813832.1588940662.1589097017.5; __utmb=223695111.0.10.1589097017; __utmc=223695111; ap_v=0,6.0; dbcl2="216584294:NBHisAJp02A"; ck=jzQy; __utmt=1; __utmv=30149280.21658; __utmb=30149280.6.10.1589097017; _pk_id.100001.4cf6=0622253e80c3deb2.1578813831.5.1589097344.1588943550.'
    line=b.split(';')
    cookie={}
    for i in line:
        key,value = i.split('=',1)
        cookie[key] = value
    response1 = requests.get(url,headers=headers,cookies=cookie)
    response1.encoding = 'utf-8'
    html = response1.json()
    html1=html["data"]
    
    name=[]
    score=[]
    pnumber=[]
    urls=[]
    cover=[]
    id=[]
    for one in html1:
        name.append(one['title'])
        score.append(one['rate'])
        pnumber.append(one['cover_y'])
        urls.append(one['url'])
        cover.append(one['cover'])
        id.append(one['id'])
    #print(urls)
    columns3={'剧名':name,'评分':score,'点评数':pnumber,'url':urls,'图片':cover,'id':id}
    data2=pd.DataFrame(columns3)

KeyError: 'data'

In [ ]:
data2.head()

In [ ]:
E=df.to_excel('G:/CDO/数据存储和获取/豆瓣动画.xlsx',encoding='utf-8')
E